# Generated by Django 4.2.1 on 2023-06-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_hourly_rate_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact_resource",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
