# Generated by Django 4.2.1 on 2023-06-07 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_alter_client_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
