# Generated by Django 4.2.1 on 2023-06-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_alter_client_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="hourly_rate",
        ),
        migrations.AddField(
            model_name="client",
            name="hourly_rate_evening",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="client",
            name="hourly_rate_morning",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="client",
            name="hourly_rate_night",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
