# Generated by Django 4.2.1 on 2023-06-08 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "clients",
            "0006_remove_client_hourly_rate_client_hourly_rate_evening_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_joined",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
