# Generated by Django 4.2.1 on 2023-06-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_alter_client_date_joined_alter_client_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="hourly_rate_evening",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="client",
            name="hourly_rate_morning",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="client",
            name="hourly_rate_night",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
