# Generated by Django 4.2.1 on 2023-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_alter_client_hourly_rate_evening_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
    ]
