# Generated by Django 4.2.1 on 2023-06-14 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_client_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_joined",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
