# Generated by Django 4.2.1 on 2023-05-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
        ("week", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWeekWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday", models.IntegerField(default=0)),
                ("tuesday", models.IntegerField(default=0)),
                ("wednesday", models.IntegerField(default=0)),
                ("thursday", models.IntegerField(default=0)),
                ("friday", models.IntegerField(default=0)),
                ("saturday", models.IntegerField(default=0)),
                ("sunday", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="week.week"
                    ),
                ),
            ],
            options={
                "unique_together": {("week", "employee")},
            },
        ),
    ]
