# Generated by Django 4.2.1 on 2023-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("week", "0002_employeeweekwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeweekwork",
            name="bonus",
            field=models.IntegerField(default=0),
        ),
    ]
