# Generated by Django 4.2.1 on 2023-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("week", "0003_employeeweekwork_bonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeweekwork",
            name="friday",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="employeeweekwork",
            name="monday",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="employeeweekwork",
            name="thursday",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="employeeweekwork",
            name="tuesday",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="employeeweekwork",
            name="wednesday",
            field=models.IntegerField(default=8),
        ),
    ]
