# Generated by Django 4.2.1 on 2023-06-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("week", "0004_alter_employeeweekwork_friday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="rate_field",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
