# Generated by Django 4.2.1 on 2023-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("week", "0006_alter_week_rate_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="rate_field",
            field=models.CharField(
                choices=[
                    ("morning_rate", "Morning Rate"),
                    ("evening_rate", "Evening Rate"),
                    ("night_rate", "Night Rate"),
                ],
                max_length=20,
            ),
        ),
    ]
