# Generated by Django 4.2.1 on 2023-05-24 18:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employee_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
